### PR TITLE
ONECOND-708: Reduce amount of logging

### PR DESCRIPTION
**Pull request by hueys**
The log messages referenced from https://jira.d3nw.com/browse/ONECOND-708 look to be because of the use of the `logger.error(String msg, Throwable t)` method. When a `Throwable` is provided and the stack trace is logged, the resulting log message contains newlines which result in the appearance of additional messages within Splunk.

It looks like this method is used elsewhere in the Conductor codebase. We need to decide whether to remove other uses of it or use a different method that removes the newlines from the underlying stack traces before logging the information.

### CODE REVIEW

**Comment by hueys** [comment]
**Example stack trace with newlines:**
```
com.netflix.conductor.core.execution.TerminateWorkflow: DEBUG
	at com.netflix.conductor.core.execution.DeciderService.checkForTimeout(DeciderService.java:360)
	at com.netflix.conductor.core.execution.DeciderService.decide(DeciderService.java:121)
	at com.netflix.conductor.core.execution.DeciderService.decide(DeciderService.java:81)
	at com.netflix.conductor.core.execution.WorkflowExecutor.decide(WorkflowExecutor.java:933)
	at com.netflix.conductor.core.execution.WorkflowSweeper.lambda$1(WorkflowSweeper.java:115)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by heajuenhwang** [comment]
I think instead of using different function remove newline for the exception before logging sounds better. @hueys  @lysakaleksey please let us know your thought.

**Comment by hueys** [comment]
…it looks like we can update the Log4J properties with a pattern layout to either replace newlines in all cases, or can specify the line separator used when logging exceptions to use something like `|` instead.

https://logging.apache.org/log4j/2.x/manual/layouts.html

**Comment by lysakaleksey** [comment]
@hueys See above comment

**Pull request merged**
